### ISSUE TITLE
Could not find a valid y-coordinate 

### ISSUE THREAD

**Issue by greenpp88** [KrashKrash/Twist-Attack-Sub-Group-Attack#2]

**Comment by greenpp88** [comment]
Hello

I found this error
"Could not find a valid y-coordinate on Twist Curve 1"

I try different address and it comes like this but on different curve. (eg. 2/3/4)

is it something wrong with the program (sagemath that i install) or perhaps not every btc address can use this method?

Thanks

**Comment by KrashKrash** [comment]
not all twisted curves are valid for every key. identify the invalid curve, remove the curve and try different twisted curves. you can add more curves or remove them in the code.

**Comment by greenpp88** [comment]
Hi.

how many curves should we try until it is valid curves? your example is 4. should I keep at 4 valid curves?

**Comment by ytrezq** [comment]
@greenpp88 attack only normally work when you make the attacker trigerring a fault.

If I were you, I would rework the script in order to find curves that preserve the order of the original curves. Small subgroups isn t the only case of vulnerable curves.
