### ISSUE TITLE
Plus PR and crt 

### ISSUE THREAD

**Issue by ThegreatUnique** [KrashKrash/Twist-Attack-Sub-Group-Attack#4]
This attack could wipe out Bitcoin sentimental value itself. Unless the blockchain data is made not to expose any data regarding the public key, then we are in for a dump

**Comment by KrashKrash** [comment]
> In what context would this attack work, what are the conditions to be met? Please illustrate with a concrete example? Thanks

when the partial private keys are combine correctly, it reveals the correct private key to the public key. as mention by ThegreatUnique, just by having knowledge of the pubx nd puby we can derive the private key. providing the full code here would jeopardize the whole BTC security. hence, i do not release the part where the full private key can be combine using custom libraries.

**Comment by ThegreatUnique** [comment]
> In what context would this attack work, what are the conditions to be met? Please illustrate with a concrete example? Thanks

Generally the attack shouldn't be studied or attempted to protect the security protocol of Bitcoin, at least for now until anyone decides to ruin the "digital gold currency" hence as krashkrash said , he will not release the part where the full private
